--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: apps-prod
  region: eu-west-1

vpc:
  id: "vpc-014a907f"
  subnets:
    private:
      eu-west-1a:
        id: "subnet-0e26a2"
      eu-west-1b:
        id: "subnet-0069713"
      eu-west-1c:
        id: "subnet-068c4a0c2"

nodeGroups:
  - name: dp-1
    kubeletExtraConfig:
        kubeReserved:
            cpu: "500m"
            memory: "500Mi"
            ephemeral-storage: "5Gi"
        kubeReservedCgroup: "/kube-reserved"
        systemReserved:
            cpu: "500m"
            memory: "500Mi"
            ephemeral-storage: "5Gi"
        evictionHard:
            memory.available:  "500Mi"
            nodefs.available: "10%"
        featureGates:
            DynamicKubeletConfig: true
            RotateKubeletServerCertificate: true
    instanceType: r4.xlarge
    ssh:
      publicKeyName: devops-test
    securityGroups:
      withShared: true
      withLocal: true
      attachIDs: ['sg-073257', 'sg-02724543']
    tags:
      k8s.io/cluster-autoscaler/enabled: "true"
      k8s.io/cluster-autoscaler/cluster-13: "owned"
    desiredCapacity: 4
    #ami: ami-04d3a39b
    minSize: 4
    maxSize: 4
    privateNetworking: true
    availabilityZones: ["eu-west-1a","eu-west-1b","eu-west-1c"]
    labels:
      nodegroup: devops
    iam:
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
        - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
        - arn:aws:iam::aws:policy/ElasticLoadBalancingFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess 
        - arn:aws:iam::aws:policy/AmazonSSMFullAccess
        - arn:aws:iam::aws:policy/AmazonEC2FullAccess
        - arn:aws:iam::aws:policy/AmazonRoute53FullAccess
      withAddonPolicies:
        albIngress: true
        autoScaler: true
        imageBuilder: true
        externalDNS: true
        certManager: true
        appMesh: true
        ebs: true
        fsx: true
        efs: true
        xRay: true
        cloudWatch: true
cloudWatch:
  clusterLogging:
    enableTypes: ["all"]
